#!/usr/bin/env bash

# usage: ./convert <input_file>

# input file argv1
input_file=$1

# output file should be same name, with .wav extension
output_file="${input_file%.*}.wav"

echo "Converting $input_file to $output_file"
sox -t raw -r 16000 -b 16 -c 1 -L -e signed-integer $input_file $output_file